fs=15;
set(0, 'DefaultAxesFontSize', fs);
figure(1);
hold on;
lx1=xlabel('Time $t$, s', 'FontSize', fs);
ly1=ylabel('Linear coordinates $m$', 'FontSize', fs);
set(lx1, 'Interpreter', 'Latex');
set(ly1, 'Interpreter', 'Latex');
plot(x_scope.time, x_scope.signals.values(:,1), 'LineWidth', 2, 'LineStyle', '-', 'Color', 'Red');
plot(y_scope.time, y_scope.signals.values(:,1), 'LineWidth', 2, 'LineStyle', '--', 'Color', 'Blue');
plot(z_scope.time, z_scope.signals.values(:,1), 'LineWidth', 2, 'LineStyle', '-.', 'Color', 'Green');
grid on;
l1=legend('$x$','$y$','$z$');
set(l1, 'Interpreter', 'Latex');
hold off;

figure(2);
hold on;
lx2=xlabel('Time $t$, s', 'FontSize', fs);
ly2=ylabel('Angular coordinates $deg$','FontSize', fs);
set(lx2, 'Interpreter', 'Latex');
set(ly2, 'Interpreter', 'Latex');
plot(phi_scope.time, phi_scope.signals.values(:,1), 'LineWidth', 2, 'LineStyle', '-', 'Color', 'Red');
plot(theta_scope.time, theta_scope.signals.values(:,1), 'LineWidth', 2, 'LineStyle', '--', 'Color', 'Blue');
plot(psi_scope.time, psi_scope.signals.values(:,1), 'LineWidth', 2, 'LineStyle', '-.', 'Color', 'Green');
grid on;
l2=legend('$phi$', '$theta$', '$psi$');
set(l2, 'Interpreter', 'Latex');
hold off;

figure(3);
hold on;
lx1=xlabel('Time $t$, s', 'FontSize', fs);
ly1=ylabel('Control parameters $\mu_x(t)$','FontSize', fs);
set(lx1, 'Interpreter', 'Latex');
set(ly1, 'Interpreter', 'Latex');
plot(mu_x.time, mu_x.signals.values(:,1), 'LineWidth', 3, 'LineStyle', '-', 'Color', 'Red');
grid on;
l1=legend('$\mu_x(t)$');
set(l1, 'Interpreter', 'Latex');
hold off;